#!/usr/bin/env node
// Syncs the bundled skills with the ones published at accounts.myclickfunnels.com.
//
//   node scripts/sync-skills.mjs          fetch the index, rewrite skills/, update skills.lock.json
//   node scripts/sync-skills.mjs --check  exit 1 if skills/ has drifted from the published digests
//
// Needs Node 18+ (global fetch). No dependencies.

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ORIGIN = "https://accounts.myclickfunnels.com";
const INDEX_URL = `${ORIGIN}/.well-known/agent-skills/index.json`;
const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SKILLS_DIR = join(ROOT, "skills");
const LOCK_PATH = join(ROOT, "skills.lock.json");
const MAIN_SKILL = join(SKILLS_DIR, "clickfunnels", "SKILL.md");
const BEGIN = "<!-- BEGIN synced-skills (generated by scripts/sync-skills.mjs) -->";
const END = "<!-- END synced-skills -->";
const NAME_PATTERN = /^[a-z0-9]+(-[a-z0-9]+)*$/;

const sha256 = (data) => createHash("sha256").update(data).digest("hex");

async function get(url) {
  const response = await fetch(url, { headers: { accept: "text/markdown, application/json" } });
  if (!response.ok) throw new Error(`GET ${url} -> ${response.status}`);
  return Buffer.from(await response.arrayBuffer());
}

// Relative links point at the accounts host. Make them absolute so they resolve from the repo.
// Only markdown links and frontmatter `path:` entries outside fenced code blocks are rewritten;
// code samples stay byte-for-byte.
function absolutize(text) {
  let fenced = false;
  let frontmatter = false;
  return text
    .split("\n")
    .map((line, index) => {
      if (line === "---" && (index === 0 || frontmatter)) {
        frontmatter = index === 0;
        return line;
      }
      if (frontmatter) return line.replace(/^(\s*-?\s*path:\s*)\/(?!\/)/, `$1${ORIGIN}/`);
      if (/^\s*(```|~~~)/.test(line)) fenced = !fenced;
      if (fenced) return line;
      return line.replace(/\]\(\/(?!\/)/g, `](${ORIGIN}/`);
    })
    .join("\n");
}

function frontmatterName(text) {
  const match = text.match(/^---\n([\s\S]*?)\n---/);
  return match?.[1].match(/^name:\s*["']?([^"'\n]+?)["']?\s*$/m)?.[1];
}

function skillsBlock(skills) {
  const lines = skills.map((skill) => {
    const summary = skill.description.split(/(?<=\.)\s/)[0];
    return `- \`${skill.name}\` (${skill.url}): ${summary}`;
  });
  return [BEGIN, ...lines, END].join("\n");
}

function withSkillsBlock(text, block) {
  const start = text.indexOf(BEGIN);
  const end = text.indexOf(END);
  if (start === -1 || end === -1) throw new Error(`${MAIN_SKILL} is missing the synced-skills markers`);
  return text.slice(0, start) + block + text.slice(end + END.length);
}

async function fetchPublished() {
  const index = JSON.parse((await get(INDEX_URL)).toString("utf8"));
  const skills = index.skills
    .filter((skill) => skill.type === "skill-md")
    .sort((a, b) => a.name.localeCompare(b.name));

  for (const skill of skills) {
    if (!NAME_PATTERN.test(skill.name)) throw new Error(`Invalid skill name: ${skill.name}`);
    if (skill.name === "clickfunnels") throw new Error("Published skill collides with the hand-written clickfunnels skill");
    if (!skill.url.startsWith(`${ORIGIN}/`)) throw new Error(`Unexpected skill host: ${skill.url}`);
  }
  return skills;
}

function readLock() {
  return existsSync(LOCK_PATH) ? JSON.parse(readFileSync(LOCK_PATH, "utf8")) : { skills: [] };
}

async function sync() {
  const published = await fetchPublished();
  const previous = readLock();
  const entries = [];

  for (const skill of published) {
    const raw = await get(skill.url);
    const digest = `sha256:${sha256(raw)}`;
    if (digest !== skill.digest) {
      throw new Error(`${skill.url} digest ${digest} does not match index ${skill.digest}. Retry once caches settle.`);
    }
    const text = raw.toString("utf8");
    const name = frontmatterName(text);
    if (name !== skill.name) throw new Error(`${skill.url} frontmatter name "${name}" does not match index "${skill.name}"`);

    const content = absolutize(text);
    const dir = join(SKILLS_DIR, skill.name);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, "SKILL.md"), content);
    entries.push({ name: skill.name, url: skill.url, digest: skill.digest, sha256: sha256(content) });
    console.log(`synced ${skill.name}`);
  }

  const kept = new Set(entries.map((entry) => entry.name));
  for (const old of previous.skills) {
    if (!kept.has(old.name)) {
      rmSync(join(SKILLS_DIR, old.name), { recursive: true, force: true });
      console.log(`removed ${old.name}`);
    }
  }

  writeFileSync(MAIN_SKILL, withSkillsBlock(readFileSync(MAIN_SKILL, "utf8"), skillsBlock(published)));
  writeFileSync(LOCK_PATH, `${JSON.stringify({ source: INDEX_URL, skills: entries }, null, 2)}\n`);
}

async function check() {
  const published = await fetchPublished();
  const lock = readLock();
  const locked = new Map(lock.skills.map((entry) => [entry.name, entry]));
  const problems = [];

  for (const skill of published) {
    const entry = locked.get(skill.name);
    if (!entry) problems.push(`${skill.name}: published but not bundled`);
    else if (entry.digest !== skill.digest || entry.url !== skill.url) problems.push(`${skill.name}: published skill changed`);
    locked.delete(skill.name);
  }
  for (const name of locked.keys()) problems.push(`${name}: bundled but no longer published`);

  for (const entry of lock.skills) {
    const path = join(SKILLS_DIR, entry.name, "SKILL.md");
    if (!existsSync(path)) problems.push(`${entry.name}: ${path} is missing`);
    else if (sha256(readFileSync(path)) !== entry.sha256) problems.push(`${entry.name}: SKILL.md was edited by hand`);
  }

  const main = readFileSync(MAIN_SKILL, "utf8");
  if (withSkillsBlock(main, skillsBlock(published)) !== main) problems.push("clickfunnels: skill list is out of date");

  if (problems.length) {
    console.error(problems.map((problem) => `- ${problem}`).join("\n"));
    console.error("\nRun `node scripts/sync-skills.mjs` to re-sync.");
    process.exit(1);
  }
  console.log(`${published.length} bundled skills match ${INDEX_URL}`);
}

(process.argv.includes("--check") ? check() : sync()).catch((error) => {
  console.error(error.message);
  process.exit(1);
});
